name: Build and deploy Spring Boot app to Azure Web App

on:
  push:
    branches:
      - main   # or master (match your repo)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: BackendServer22
          publish-profile: ${{ secrets.AZURE_Backend_PUBLISH_PROFILE }}
          package: target/*.jar
